version: "3"
services:
  db-master:
    container_name: ${MASTER_CONTAINER_NAME}
    privileged: true
    build:
      context: ./
      dockerfile: master/Dockerfile
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_REMOTE_USER_MASTER}
      MYSQL_PASSWORD: ${MYSQL_REMOTE_USER_PASSWORD_MASTER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - '${EXPOSE_PORT_MASTER}:3306'
    # Where our data will be persisted
    volumes:
      - ${MYSQL_DATA_PATH_MASTER}:/var/lib/mysql
      - ${MYSQL_FILE_PATH_MASTER}:/var/lib/mysql-files
      - ${MYSQL_LOG_PATH_MASTER}:/var/log/mysql
      - ${MYSQL_ETC_PATH_MASTER}:/var/tmp
      - ./master/my.cnf:/etc/mysql/my.cnf
    networks:
      - net-mysql
  
  db-slave:
    container_name: ${SLAVE_CONTAINER_NAME}
    privileged: true
    build:
      context: ./
      dockerfile: slave/Dockerfile
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_REMOTE_USER_SLAVE}
      MYSQL_PASSWORD: ${MYSQL_REMOTE_USER_PASSWORD_SLAVE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - '${EXPOSE_PORT_SLAVE}:3306'
    # Where our data will be persisted
    volumes:
      - ${MYSQL_DATA_PATH_SLAVE}:/var/lib/mysql
      - ${MYSQL_FILE_PATH_SLAVE}:/var/lib/mysql-files
      - ${MYSQL_LOG_PATH_SLAVE}:/var/log/mysql
      - ${MYSQL_ETC_PATH_SLAVE}:/var/tmp
      - ./slave/my.cnf:/etc/mysql/my.cnf
    networks:
      - net-mysql
  
# Names our volume
volumes:
  my-db-master:
  my-db-slave: 

networks:
  net-mysql:
    driver: bridge
